// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZDyXxcGIjhCnM_Vr5M15Ymth3J25e7Q',
    appId: '1:495005222139:web:9b66fc460c8ecaf6d25c5e',
    messagingSenderId: '495005222139',
    projectId: 'fir-demo-project-a0aab',
    authDomain: 'fir-demo-project-a0aab.firebaseapp.com',
    storageBucket: 'fir-demo-project-a0aab.appspot.com',
    measurementId: 'G-DX0CD6QXG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KOC9q0mOjDZe0Jyach5wBQtibZUZP4s',
    appId: '1:495005222139:android:aeee610efd460e1cd25c5e',
    messagingSenderId: '495005222139',
    projectId: 'fir-demo-project-a0aab',
    storageBucket: 'fir-demo-project-a0aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4es1vzZ0fWb4vL_Iee5idtwr4kFXz6Do',
    appId: '1:495005222139:ios:230324a8bd9edc4ed25c5e',
    messagingSenderId: '495005222139',
    projectId: 'fir-demo-project-a0aab',
    storageBucket: 'fir-demo-project-a0aab.appspot.com',
    iosClientId: '495005222139-4musv4rlphet3tusj7i09v01u649q2sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kamilnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4es1vzZ0fWb4vL_Iee5idtwr4kFXz6Do',
    appId: '1:495005222139:ios:230324a8bd9edc4ed25c5e',
    messagingSenderId: '495005222139',
    projectId: 'fir-demo-project-a0aab',
    storageBucket: 'fir-demo-project-a0aab.appspot.com',
    iosClientId: '495005222139-4musv4rlphet3tusj7i09v01u649q2sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kamilnotes',
  );
}
